### ISSUE TITLE
Delay is too large when hardware reset.

### ISSUE THREAD

**Issue by Tnze** [caemor/epd-waveshare#113]
According to [this specification](https://www.waveshare.net/w/upload/e/ec/2.66inch-e-paper-b-specification.pdf#13.2), delay between RESE low and RESE high should be 200us. But the `DELAY` is a `DelayMs<u8>` [here](https://github.com/caemor/epd-waveshare/blob/e36c134d8af4dff5d1d780296d08345042440bf2/src/interface.rs#L177).

**Comment by caemor** [comment]
We need to change delay to DelayUS<u32> to be able to use the `us` range as well as up to ~100ms

**Comment by peckpeck** [comment]
The way forward is `DelayUs<32>` because it's the only trait supported in embedded-hal 1.0

**Comment by peckpeck** [comment]
https://github.com/caemor/epd-waveshare/pull/131

**Comment by caemor** [comment]
Hello @Tnze,
this should be resolved by Peckpecks PR in #131 where DelayMs<u8> was replaced by DelayUs<u32>
