### ISSUE TITLE
Why do we have to handle CS pin

### ISSUE THREAD

**Issue by peckpeck** [caemor/epd-waveshare#116]
SPI should already handle setting the CS pin during communication, why do we have to handle it inside the library's interface mod ?

**Comment by caemor** [comment]
The old spi trait didn't make any assertions about the cs pin so we needed to manually handle it, with the new [`SPIDevice`](https://docs.rs/embedded-hal/1.0.0-alpha.9/embedded_hal/spi/index.html#for-driver-authors) trait we can solve it directly by using the hal.

**Comment by caemor** [comment]
Resolved by using eh-1.0
