### ISSUE TITLE
Dividing the dims by 8

### ISSUE THREAD

**Issue by David-OConnor** [caemor/epd-waveshare#50]
Question: What is the purpose of dividing the dims by 8 when creating the buffer? eg:
```rust
pub struct Display4in2 {
    buffer: [u8; WIDTH as usize * HEIGHT as usize / 8],
    rotation: DisplayRotation,
}
```
With this in mind, how should you map pixels to the buffer, given it's not a 1:1 match? Thank you.

**Comment by caemor** [comment]
Each pixel only has 1 bit of info about it stored (Is it black or white). So we can put 8 Pixel in one Byte/u8 and therefore reduce storage.

**Comment by David-OConnor** [comment]
Thank you. That answers my question.
