### ISSUE TITLE
new release to crates.io

### ISSUE THREAD

**Issue by nivpgir** [caemor/epd-waveshare#89]
Is it possible to get a new release to crates.io? I'm using the 2in13 display and it would be nice to use it from crates.io instead of github.

plus it's been about a year since the last release so the embedded-graphics versions in crates.io are outdated as well.

**Comment by caemor** [comment]
Sure, will try to publish a new release this upcoming weekend.

**Comment by caemor** [comment]
New version (0.5) is released. The next release afterward (1.0?) should be shortly after the eh 1.0 release
