### ISSUE TITLE
Unable to compile test suite on windows host

### ISSUE THREAD

**Issue by akashihi** [caemor/epd-waveshare#94]
Dev build depends on `linux-embedded-hal` which brings non-portable crates, such as `gpio-cdev`, `spidev`, `sysfs-gpio` and `serial-unix` which prevents compilation and execution of unit tests on windows. 

As  `linux-embedded-hal` is only used for the example code, both example code build and `linux-embedded-hal` dependency could be a default feature, which can be disabled on the windows platform.

**Comment by caemor** [comment]
I tried to fix this today by making `linux-embedded-hal` an optional dev-dependency but this is currently not possible (see https://github.com/rust-lang/cargo/issues/1596). 
One possible solution would be the move to an optional dependency which makes it worse from my point of view.
Another solution might be the move to a workspace and to move the examples to their own "crate".

Would be happy to receive some feedback and maybe an even better and more elegant solution for this problem.
