### ISSUE TITLE
Note about const generics

### ISSUE THREAD

**Issue by Liamolucko** [caemor/epd-waveshare#99]
There's a note in `WaveshareDisplay::draw_helper`:
https://github.com/caemor/epd-waveshare/blob/f49b6e98f52f4bd5dbde35bea7c18379f8bb4416/src/graphics.rs#L72-L73

`min_const_generics` was stabilised in rust 1.51, so this could probably be resolved if that's an acceptable MSRV; what's it referring to? 
Is it the duplication of `Display` for each model?

**Comment by caemor** [comment]
MSRV is the most recent stable rust release.
> Is it the duplication of Display for each model?
Yes I believe so, but I can't fully remember what I meant there :-D

**Comment by caemor** [comment]
Note got remove, const generics are in use for the Display Struct.
